import 'dart:io';

import 'package:final_project/Constants/colors.dart';
import 'package:final_project/Constants/currency_formatter.dart';
import 'package:final_project/Primary_Screens/Budgets/budget_model.dart';
import 'package:final_project/Primary_Screens/Savings/saving_model.dart';
import 'package:final_project/Primary_Screens/analytics_page/analytics_helpers.dart';
import 'package:final_project/SecondaryScreens/Report/report_page.dart' hide Budget;
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';



class AnalyticsPdfService {
  final String selectedFilter;
  final double filteredIncome;
  final double filteredExpenses;
  final double filteredSavings;
  final double netBalance;
  final double savingsRate;
  final double expenseRatio;
  final double avgDailySpend;
  final double totalFeesPaid;
  final double projectedMonthEndSpend;
  final List<Map<String, dynamic>> last6MonthsData;
  final Map<String, double> expensesByCategory;
  final Map<String, dynamic> monthlyComparison;
  final List<Budget> budgets;
  final List<Saving> savings;
  final List<Map<String, dynamic>> smartInsights;

  const AnalyticsPdfService({
    required this.selectedFilter,
    required this.filteredIncome,
    required this.filteredExpenses,
    required this.filteredSavings,
    required this.netBalance,
    required this.savingsRate,
    required this.expenseRatio,
    required this.avgDailySpend,
    required this.totalFeesPaid,
    required this.projectedMonthEndSpend,
    required this.last6MonthsData,
    required this.expensesByCategory,
    required this.monthlyComparison,
    required this.budgets,
    required this.savings,
    required this.smartInsights,
  });

  Future<void> generate(BuildContext context) async {
    try {
      final pdf = pw.Document();
      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(32),
          build: (ctx) => [
            _pdfHeader(),
            pw.SizedBox(height: 20),
            _pdfSectionTitle('Financial Overview'),
            pw.SizedBox(height: 10),
            _pdfSummary(),
            pw.SizedBox(height: 20),
            _pdfSectionTitle('Income vs Expenses (6-month trend)'),
            pw.SizedBox(height: 10),
            _pdfBarChart(),
            pw.SizedBox(height: 20),
            if (expensesByCategory.isNotEmpty) ...[
              _pdfSectionTitle('Spending by Category'),
              pw.SizedBox(height: 10),
              _pdfCategoryChart(),
              pw.SizedBox(height: 20),
            ],
            _pdfSectionTitle('Monthly Comparison'),
            pw.SizedBox(height: 10),
            _pdfMonthlyComparison(),
            pw.SizedBox(height: 20),
            if (budgets.isNotEmpty) ...[
              _pdfSectionTitle('Budget Health'),
              pw.SizedBox(height: 10),
              _pdfBudgetHealth(),
              pw.SizedBox(height: 20),
            ],
            if (savings.isNotEmpty) ...[
              _pdfSectionTitle('Savings Goals'),
              pw.SizedBox(height: 10),
              _pdfSavingsGoals(),
              pw.SizedBox(height: 20),
            ],
            _pdfSectionTitle('Smart Insights'),
            pw.SizedBox(height: 10),
            _pdfInsights(),
            pw.SizedBox(height: 24),
            pw.Divider(),
            pw.Center(
              child: pw.Text(
                'Generated by Penny Finance App',
                style: const pw.TextStyle(
                  fontSize: 9,
                  color: PdfColors.grey600,
                ),
              ),
            ),
          ],
        ),
      );

      final bytes = await pdf.save();
      final fileName =
          'penny_analytics_${DateFormat('yyyyMMdd_HHmmss').format(DateTime.now())}.pdf';
      final tempDir = await getTemporaryDirectory();
      final file = File('${tempDir.path}/$fileName');
      await file.writeAsBytes(bytes);
      await Share.shareXFiles([XFile(file.path)], subject: 'Penny Finance Analytics');

      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Row(
              children: [
                Icon(Icons.share, color: Colors.white),
                SizedBox(width: 8),
                Text('Opening share…'),
              ],
            ),
            backgroundColor: accentColor,
            behavior: SnackBarBehavior.floating,
            duration: Duration(seconds: 2),
          ),
        );
      }
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('PDF error: $e'),
            backgroundColor: errorColor,
          ),
        );
      }
      rethrow;
    }
  }

  pw.Widget _pdfSectionTitle(String t) => pw.Text(
    t,
    style: pw.TextStyle(fontSize: 15, fontWeight: pw.FontWeight.bold),
  );

  pw.Widget _pdfHeader() => pw.Column(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      pw.Text(
        'Penny Finance Analytics Report',
        style: pw.TextStyle(
          fontSize: 22,
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.blue900,
        ),
      ),
      pw.SizedBox(height: 5),
      pw.Text(
        'Period: $selectedFilter   Generated: ${DateFormat('dd MMM yyyy HH:mm').format(DateTime.now())}',
        style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
      ),
    ],
  );

  pw.Widget _pdfSummary() => pw.Container(
    padding: const pw.EdgeInsets.all(14),
    decoration: pw.BoxDecoration(
      border: pw.Border.all(color: PdfColors.grey300),
      borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
    ),
    child: pw.Column(
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            _pdfKpi('Income', filteredIncome, PdfColors.green),
            _pdfKpi('Expenses', filteredExpenses, PdfColors.red),
            _pdfKpi('Savings', filteredSavings, PdfColors.blue),
            _pdfKpi(
              'Net Balance',
              netBalance,
              netBalance >= 0 ? PdfColors.green : PdfColors.red,
            ),
          ],
        ),
        pw.SizedBox(height: 10),
        pw.Divider(),
        pw.SizedBox(height: 5),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Savings Rate: ${savingsRate.toStringAsFixed(1)}%',
              style: const pw.TextStyle(fontSize: 10),
            ),
            pw.Text(
              'Expense Ratio: ${expenseRatio.toStringAsFixed(1)}%',
              style: const pw.TextStyle(fontSize: 10),
            ),
            pw.Text(
              'Avg Daily: ${CurrencyFormatter.format(avgDailySpend)}',
              style: const pw.TextStyle(fontSize: 10),
            ),
            pw.Text(
              'Fees: ${CurrencyFormatter.format(totalFeesPaid)}',
              style: const pw.TextStyle(fontSize: 10),
            ),
          ],
        ),
      ],
    ),
  );

  pw.Widget _pdfKpi(String label, double amount, PdfColor color) => pw.Column(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      pw.Text(
        label,
        style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
      ),
      pw.SizedBox(height: 3),
      pw.Text(
        CurrencyFormatter.format(amount),
        style: pw.TextStyle(
          fontSize: 12,
          fontWeight: pw.FontWeight.bold,
          color: color,
        ),
      ),
    ],
  );

  pw.Widget _pdfBarChart() {
    final data = last6MonthsData;
    final maxVal = data.fold(
      0.0,
      (m, d) => [
        m,
        d['income'] as double,
        d['expenses'] as double,
      ].reduce((a, b) => a > b ? a : b),
    );
    if (maxVal == 0) {
      return pw.Text('No data', style: const pw.TextStyle(fontSize: 10));
    }

    return pw.Container(
      height: 180,
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.end,
        mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
        children: data.map((d) {
          final incH = 130 * ((d['income'] as double) / maxVal);
          final expH = 130 * ((d['expenses'] as double) / maxVal);
          return pw.Column(
            mainAxisAlignment: pw.MainAxisAlignment.end,
            children: [
              pw.Row(
                crossAxisAlignment: pw.CrossAxisAlignment.end,
                children: [
                  pw.Container(
                    width: 10,
                    height: incH,
                    color: PdfColors.green300,
                  ),
                  pw.SizedBox(width: 2),
                  pw.Container(
                    width: 10,
                    height: expH,
                    color: PdfColors.red300,
                  ),
                ],
              ),
              pw.SizedBox(height: 4),
              pw.Text(
                d['label'] as String,
                style: const pw.TextStyle(fontSize: 8),
              ),
            ],
          );
        }).toList(),
      ),
    );
  }

  pw.Widget _pdfCategoryChart() {
    final cats = expensesByCategory;
    final total = cats.values.fold(0.0, (s, v) => s + v);
    if (total == 0) {
      return pw.Text('No data', style: const pw.TextStyle(fontSize: 10));
    }

    final pdfColors = [
      PdfColors.blue,
      PdfColors.orange,
      PdfColors.purple,
      PdfColors.green,
      PdfColors.red,
      PdfColors.teal,
    ];

    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Column(
        children: cats.entries.toList().asMap().entries.map((entry) {
          final idx = entry.key;
          final e = entry.value;
          final pct = total > 0 ? e.value / total * 100 : 0.0;
          final col = pdfColors[idx % pdfColors.length];
          return pw.Padding(
            padding: const pw.EdgeInsets.only(bottom: 8),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Row(
                      children: [
                        pw.Container(
                          width: 8,
                          height: 8,
                          decoration: pw.BoxDecoration(
                            color: col,
                            shape: pw.BoxShape.circle,
                          ),
                        ),
                        pw.SizedBox(width: 6),
                        pw.Text(e.key, style: const pw.TextStyle(fontSize: 10)),
                      ],
                    ),
                    pw.Text(
                      '${pct.toStringAsFixed(0)}%  ${CurrencyFormatter.compact(e.value)}',
                      style: pw.TextStyle(
                        fontSize: 10,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                  ],
                ),
                pw.SizedBox(height: 3),
                pw.Container(
                  height: 5,
                  width: pct * 3.5,
                  decoration: pw.BoxDecoration(
                    color: col,
                    borderRadius: const pw.BorderRadius.all(
                      pw.Radius.circular(3),
                    ),
                  ),
                ),
              ],
            ),
          );
        }).toList(),
      ),
    );
  }

  pw.Widget _pdfMonthlyComparison() {
    final cmp = monthlyComparison;
    final change = cmp['change'] as double;
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Column(
        children: [
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
            children: [
              _pdfKpi(
                'This Month Expenses',
                cmp['thisMonthExp'],
                PdfColors.red,
              ),
              _pdfKpi(
                'Last Month Expenses',
                cmp['lastMonthExp'],
                PdfColors.grey600,
              ),
              _pdfKpi(
                'This Month Income',
                cmp['thisMonthInc'],
                PdfColors.green,
              ),
            ],
          ),
          pw.SizedBox(height: 8),
          pw.Container(
            padding: const pw.EdgeInsets.all(8),
            decoration: pw.BoxDecoration(
              color: change > 0 ? PdfColors.red50 : PdfColors.green50,
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
            ),
            child: pw.Text(
              '${change.abs().toStringAsFixed(1)}% ${change > 0 ? 'increase' : 'decrease'} in spending vs last month',
              style: pw.TextStyle(
                fontSize: 10,
                color: change > 0 ? PdfColors.red : PdfColors.green,
              ),
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget _pdfBudgetHealth() => pw.Table(
    border: pw.TableBorder.all(color: PdfColors.grey300),
    children: [
      pw.TableRow(
        decoration: const pw.BoxDecoration(color: PdfColors.grey200),
        children:
            ['Budget', 'Allocated', 'Spent', 'Remaining', 'Usage', 'Status']
                .map(
                  (h) => pw.Padding(
                    padding: const pw.EdgeInsets.all(6),
                    child: pw.Text(
                      h,
                      style: pw.TextStyle(
                        fontSize: 9,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                  ),
                )
                .toList(),
      ),
      ...budgets.map((b) {
        final pct = b.total > 0 ? b.totalSpent / b.total * 100 : 0.0;
        final col = pct < 70
            ? PdfColors.green
            : pct < 90
            ? PdfColors.orange
            : PdfColors.red;
        return pw.TableRow(
          children: [
            pw.Padding(
              padding: const pw.EdgeInsets.all(5),
              child: pw.Text(b.name, style: const pw.TextStyle(fontSize: 9)),
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.all(5),
              child: pw.Text(
                CurrencyFormatter.format(b.total),
                style: const pw.TextStyle(fontSize: 9),
              ),
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.all(5),
              child: pw.Text(
                CurrencyFormatter.format(b.totalSpent),
                style: const pw.TextStyle(fontSize: 9),
              ),
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.all(5),
              child: pw.Text(
                CurrencyFormatter.format(b.amountLeft),
                style: const pw.TextStyle(fontSize: 9),
              ),
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.all(5),
              child: pw.Text(
                '${pct.toStringAsFixed(0)}%',
                style: pw.TextStyle(fontSize: 9, color: col),
              ),
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.all(5),
              child: pw.Text(
                budgetHealthLabel(b),
                style: pw.TextStyle(fontSize: 9, color: col),
              ),
            ),
          ],
        );
      }),
    ],
  );

  pw.Widget _pdfSavingsGoals() => pw.Table(
    border: pw.TableBorder.all(color: PdfColors.grey300),
    children: [
      pw.TableRow(
        decoration: const pw.BoxDecoration(color: PdfColors.grey200),
        children: [
              'Goal',
              'Target',
              'Saved',
              'Left',
              'Progress',
              'Deadline',
              'Status',
            ]
                .map(
                  (h) => pw.Padding(
                    padding: const pw.EdgeInsets.all(6),
                    child: pw.Text(
                      h,
                      style: pw.TextStyle(
                        fontSize: 9,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                  ),
                )
                .toList(),
      ),
      ...savings.map((s) {
        final pct = s.progressPercent * 100;
        return pw.TableRow(
          children: [
            pw.Padding(
              padding: const pw.EdgeInsets.all(5),
              child: pw.Text(s.name, style: const pw.TextStyle(fontSize: 9)),
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.all(5),
              child: pw.Text(
                CurrencyFormatter.format(s.targetAmount),
                style: const pw.TextStyle(fontSize: 9),
              ),
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.all(5),
              child: pw.Text(
                CurrencyFormatter.format(s.savedAmount),
                style: const pw.TextStyle(fontSize: 9),
              ),
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.all(5),
              child: pw.Text(
                CurrencyFormatter.format(s.balance.clamp(0, double.infinity)),
                style: const pw.TextStyle(fontSize: 9),
              ),
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.all(5),
              child: pw.Text(
                '${pct.toStringAsFixed(0)}%',
                style: const pw.TextStyle(fontSize: 9),
              ),
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.all(5),
              child: pw.Text(
                DateFormat('dd MMM yy').format(s.deadline),
                style: const pw.TextStyle(fontSize: 9),
              ),
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.all(5),
              child: pw.Text(
                s.achieved ? 'Done ✓' : 'Active',
                style: pw.TextStyle(
                  fontSize: 9,
                  color: s.achieved ? PdfColors.green : PdfColors.grey,
                ),
              ),
            ),
          ],
        );
      }),
    ],
  );

  pw.Widget _pdfInsights() {
    return pw.Container(
      padding: const pw.EdgeInsets.all(14),
      decoration: pw.BoxDecoration(
        color: PdfColors.blue50,
        border: pw.Border.all(color: PdfColors.blue300),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: smartInsights
            .map(
              (i) => pw.Padding(
                padding: const pw.EdgeInsets.only(bottom: 8),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      i['title'] as String,
                      style: pw.TextStyle(
                        fontSize: 10,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.blue900,
                      ),
                    ),
                    pw.SizedBox(height: 2),
                    pw.Text(
                      i['detail'] as String,
                      style: const pw.TextStyle(
                        fontSize: 9,
                        color: PdfColors.grey700,
                      ),
                    ),
                  ],
                ),
              ),
            )
            .toList(),
      ),
    );
  }
}
