import 'dart:io';

import 'package:final_project/Constants/colors.dart';
import 'package:final_project/Constants/currency_formatter.dart';
import 'package:final_project/Primary_Screens/Budgets/budget_model.dart';
import 'package:final_project/Primary_Screens/Savings/saving_model.dart';
import 'package:final_project/SecondaryScreens/Report/report_helpers.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';



// ─── Report PDF Service ───────────────────────────────────────────────────────
class ReportPdfService {
  final DateTime startDate;
  final DateTime endDate;
  final List<Map<String, dynamic>> filteredTransactions;
  final double filteredIncome;
  final double filteredExpenses;
  final double filteredSavings;
  final double netBalance;
  final double avgDailySpend;
  final double totalFeesPaid;
  final double savingsRate;
  final Map<String, double> spendingByCategory;
  final List<Budget> budgets;
  final List<Saving> savings;

  const ReportPdfService({
    required this.startDate,
    required this.endDate,
    required this.filteredTransactions,
    required this.filteredIncome,
    required this.filteredExpenses,
    required this.filteredSavings,
    required this.netBalance,
    required this.avgDailySpend,
    required this.totalFeesPaid,
    required this.savingsRate,
    required this.spendingByCategory,
    required this.budgets,
    required this.savings,
  });

  // ─── Generate & share PDF ────────────────────────────────────────────────────
  Future<void> generate(BuildContext context) async {
    try {
      final pdf = pw.Document();
      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(32),
          build: (ctx) => [
            _pdfHeader(),
            pw.SizedBox(height: 20),
            _pdfSectionTitle('Financial Summary'),
            pw.SizedBox(height: 10),
            _pdfSummary(),
            pw.SizedBox(height: 20),
            _pdfSectionTitle('Spending Breakdown'),
            pw.SizedBox(height: 10),
            _pdfCategoryBreakdown(),
            if (budgets.isNotEmpty) ...[
              pw.SizedBox(height: 20),
              _pdfSectionTitle('Budget Utilisation'),
              pw.SizedBox(height: 10),
              _pdfBudgetsTable(),
            ],
            if (savings.isNotEmpty) ...[
              pw.SizedBox(height: 20),
              _pdfSectionTitle('Savings Goals'),
              pw.SizedBox(height: 10),
              _pdfSavingsTable(),
            ],
            pw.SizedBox(height: 20),
            _pdfSectionTitle('Transaction Details'),
            pw.SizedBox(height: 10),
            _pdfTransactionTable(),
            pw.SizedBox(height: 24),
            pw.Divider(),
            pw.Center(
              child: pw.Text(
                'Generated by Penny Finance App',
                style: const pw.TextStyle(
                  fontSize: 9,
                  color: PdfColors.grey600,
                ),
              ),
            ),
          ],
        ),
      );
      final bytes = await pdf.save();
      final fileName =
          'penny_report_${DateFormat('yyyyMMdd_HHmmss').format(DateTime.now())}.pdf';
      final tempDir = await getTemporaryDirectory();
      final file = File('${tempDir.path}/$fileName');
      await file.writeAsBytes(bytes);
      await Share.shareXFiles([XFile(file.path)], subject: 'Penny Finance Report');
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Row(
              children: [
                Icon(Icons.share, color: Colors.white),
                SizedBox(width: 8),
                Text('Opening share dialog...'),
              ],
            ),
            backgroundColor: accentColor,
            behavior: SnackBarBehavior.floating,
            duration: Duration(seconds: 2),
          ),
        );
      }
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('PDF error: $e'),
            backgroundColor: errorColor,
          ),
        );
      }
    }
  }

  // ─── PDF section title ────────────────────────────────────────────────────────
  pw.Widget _pdfSectionTitle(String t) => pw.Text(
    t,
    style: pw.TextStyle(fontSize: 15, fontWeight: pw.FontWeight.bold),
  );

  // ─── PDF header ───────────────────────────────────────────────────────────────
  pw.Widget _pdfHeader() => pw.Column(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      pw.Text(
        'Penny Finance Report',
        style: pw.TextStyle(
          fontSize: 22,
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.blue900,
        ),
      ),
      pw.SizedBox(height: 6),
      pw.Text(
        'Period: ${DateFormat('dd MMM yyyy').format(startDate)} – ${DateFormat('dd MMM yyyy').format(endDate)}',
        style: const pw.TextStyle(fontSize: 11, color: PdfColors.grey700),
      ),
      pw.Text(
        'Generated: ${DateFormat('dd MMM yyyy HH:mm').format(DateTime.now())}',
        style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
      ),
    ],
  );

  // ─── PDF summary ──────────────────────────────────────────────────────────────
  pw.Widget _pdfSummary() => pw.Container(
    padding: const pw.EdgeInsets.all(14),
    decoration: pw.BoxDecoration(
      border: pw.Border.all(color: PdfColors.grey300),
      borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
    ),
    child: pw.Column(
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            _pdfKpi('Total Income', filteredIncome, PdfColors.green),
            _pdfKpi('Total Expenses', filteredExpenses, PdfColors.red),
            _pdfKpi('Savings', filteredSavings, PdfColors.blue),
            _pdfKpi(
              'Net Balance',
              netBalance,
              netBalance >= 0 ? PdfColors.green : PdfColors.red,
            ),
          ],
        ),
        pw.SizedBox(height: 10),
        pw.Divider(),
        pw.SizedBox(height: 6),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Transactions: ${filteredTransactions.length}',
              style: const pw.TextStyle(fontSize: 10),
            ),
            pw.Text(
              'Avg Daily Spend: ${CurrencyFormatter.format(avgDailySpend)}',
              style: const pw.TextStyle(fontSize: 10),
            ),
            pw.Text(
              'Total Fees: ${CurrencyFormatter.format(totalFeesPaid)}',
              style: const pw.TextStyle(fontSize: 10),
            ),
            pw.Text(
              'Savings Rate: ${savingsRate.toStringAsFixed(1)}%',
              style: const pw.TextStyle(fontSize: 10),
            ),
          ],
        ),
      ],
    ),
  );

  // ─── PDF KPI block ────────────────────────────────────────────────────────────
  pw.Widget _pdfKpi(String label, double amount, PdfColor color) => pw.Column(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      pw.Text(
        label,
        style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
      ),
      pw.SizedBox(height: 3),
      pw.Text(
        CurrencyFormatter.format(amount),
        style: pw.TextStyle(
          fontSize: 12,
          fontWeight: pw.FontWeight.bold,
          color: color,
        ),
      ),
    ],
  );

  // ─── PDF category breakdown ───────────────────────────────────────────────────
  pw.Widget _pdfCategoryBreakdown() {
    final cats = spendingByCategory;
    if (cats.isEmpty) {
      return pw.Text(
        'No spending data',
        style: const pw.TextStyle(fontSize: 10),
      );
    }
    final total = cats.values.fold(0.0, (s, v) => s + v);
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Column(
        children: cats.entries.map((e) {
          final pct = total > 0 ? (e.value / total * 100) : 0.0;
          return pw.Padding(
            padding: const pw.EdgeInsets.only(bottom: 8),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(e.key, style: const pw.TextStyle(fontSize: 10)),
                    pw.Text(
                      '${pct.toStringAsFixed(0)}%  ${CurrencyFormatter.format(e.value)}',
                      style: pw.TextStyle(
                        fontSize: 10,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                  ],
                ),
                pw.SizedBox(height: 3),
                pw.Container(
                  height: 6,
                  width: pct * 4,
                  decoration: pw.BoxDecoration(
                    color: PdfColors.blue,
                    borderRadius: const pw.BorderRadius.all(
                      pw.Radius.circular(3),
                    ),
                  ),
                ),
              ],
            ),
          );
        }).toList(),
      ),
    );
  }

  // ─── PDF budgets table ────────────────────────────────────────────────────────
  pw.Widget _pdfBudgetsTable() => pw.Table(
    border: pw.TableBorder.all(color: PdfColors.grey300),
    children: [
      pw.TableRow(
        decoration: const pw.BoxDecoration(color: PdfColors.grey200),
        children: ['Budget', 'Total', 'Spent', 'Remaining', 'Usage']
            .map(
              (h) => pw.Padding(
                padding: const pw.EdgeInsets.all(6),
                child: pw.Text(
                  h,
                  style: pw.TextStyle(
                    fontSize: 9,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ),
            )
            .toList(),
      ),
      ...budgets.map((b) {
        final pct = b.total > 0 ? (b.totalSpent / b.total * 100) : 0.0;
        return pw.TableRow(
          children: [
            pw.Padding(
              padding: const pw.EdgeInsets.all(6),
              child: pw.Text(b.name, style: const pw.TextStyle(fontSize: 9)),
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.all(6),
              child: pw.Text(
                CurrencyFormatter.format(b.total),
                style: const pw.TextStyle(fontSize: 9),
              ),
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.all(6),
              child: pw.Text(
                CurrencyFormatter.format(b.totalSpent),
                style: const pw.TextStyle(fontSize: 9),
              ),
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.all(6),
              child: pw.Text(
                CurrencyFormatter.format(b.amountLeft),
                style: const pw.TextStyle(fontSize: 9),
              ),
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.all(6),
              child: pw.Text(
                '${pct.toStringAsFixed(0)}%',
                style: const pw.TextStyle(fontSize: 9),
              ),
            ),
          ],
        );
      }),
    ],
  );

  // ─── PDF savings table ────────────────────────────────────────────────────────
  pw.Widget _pdfSavingsTable() => pw.Table(
    border: pw.TableBorder.all(color: PdfColors.grey300),
    children: [
      pw.TableRow(
        decoration: const pw.BoxDecoration(color: PdfColors.grey200),
        children:
            ['Goal', 'Target', 'Saved', 'Remaining', 'Progress', 'Deadline']
                .map(
                  (h) => pw.Padding(
                    padding: const pw.EdgeInsets.all(6),
                    child: pw.Text(
                      h,
                      style: pw.TextStyle(
                        fontSize: 9,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                  ),
                )
                .toList(),
      ),
      ...savings.map((s) {
        final pct = s.targetAmount > 0
            ? (s.savedAmount / s.targetAmount * 100).clamp(0.0, 100.0)
            : 0.0;
        return pw.TableRow(
          children: [
            pw.Padding(
              padding: const pw.EdgeInsets.all(6),
              child: pw.Text(s.name, style: const pw.TextStyle(fontSize: 9)),
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.all(6),
              child: pw.Text(
                CurrencyFormatter.format(s.targetAmount),
                style: const pw.TextStyle(fontSize: 9),
              ),
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.all(6),
              child: pw.Text(
                CurrencyFormatter.format(s.savedAmount),
                style: const pw.TextStyle(fontSize: 9),
              ),
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.all(6),
              child: pw.Text(
                CurrencyFormatter.format(s.balance),
                style: const pw.TextStyle(fontSize: 9),
              ),
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.all(6),
              child: pw.Text(
                '${pct.toStringAsFixed(0)}%',
                style: const pw.TextStyle(fontSize: 9),
              ),
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.all(6),
              child: pw.Text(
                DateFormat('dd MMM yyyy').format(s.deadline),
                style: const pw.TextStyle(fontSize: 9),
              ),
            ),
          ],
        );
      }),
    ],
  );

  // ─── PDF transaction table ────────────────────────────────────────────────────
  pw.Widget _pdfTransactionTable() {
    final txList = filteredTransactions.take(100).toList();
    if (txList.isEmpty) {
      return pw.Text(
        'No transactions found',
        style: const pw.TextStyle(fontSize: 10),
      );
    }
    return pw.Column(
      children: [
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey300),
          columnWidths: const {
            0: pw.FractionColumnWidth(0.15),
            1: pw.FractionColumnWidth(0.35),
            2: pw.FractionColumnWidth(0.15),
            3: pw.FractionColumnWidth(0.15),
            4: pw.FractionColumnWidth(0.2),
          },
          children: [
            pw.TableRow(
              decoration: const pw.BoxDecoration(color: PdfColors.grey200),
              children: ['Date', 'Description', 'Type', 'Fee', 'Amount']
                  .map(
                    (h) => pw.Padding(
                      padding: const pw.EdgeInsets.all(6),
                      child: pw.Text(
                        h,
                        style: pw.TextStyle(
                          fontSize: 9,
                          fontWeight: pw.FontWeight.bold,
                        ),
                      ),
                    ),
                  )
                  .toList(),
            ),
            ...txList.map((tx) {
              final d = DateTime.parse(tx['date']);
              final amt = reportAmt(tx);
              final fee = reportFee(tx);
              final isIncome = tx['type'] == 'income';
              return pw.TableRow(
                children: [
                  pw.Padding(
                    padding: const pw.EdgeInsets.all(5),
                    child: pw.Text(
                      DateFormat('dd/MM/yy').format(d),
                      style: const pw.TextStyle(fontSize: 8),
                    ),
                  ),
                  pw.Padding(
                    padding: const pw.EdgeInsets.all(5),
                    child: pw.Text(
                      tx['title'] ?? '',
                      style: const pw.TextStyle(fontSize: 8),
                    ),
                  ),
                  pw.Padding(
                    padding: const pw.EdgeInsets.all(5),
                    child: pw.Text(
                      getTypeLabel(tx['type']),
                      style: const pw.TextStyle(fontSize: 8),
                    ),
                  ),
                  pw.Padding(
                    padding: const pw.EdgeInsets.all(5),
                    child: pw.Text(
                      fee > 0 ? CurrencyFormatter.format(fee) : '-',
                      style: const pw.TextStyle(fontSize: 8),
                    ),
                  ),
                  pw.Padding(
                    padding: const pw.EdgeInsets.all(5),
                    child: pw.Text(
                      '${isIncome ? '+' : '-'} ${CurrencyFormatter.format(isIncome ? amt : amt + fee)}',
                      style: pw.TextStyle(
                        fontSize: 8,
                        color: isIncome ? PdfColors.green : PdfColors.red,
                      ),
                    ),
                  ),
                ],
              );
            }),
          ],
        ),
        if (filteredTransactions.length > 100)
          pw.Padding(
            padding: const pw.EdgeInsets.only(top: 6),
            child: pw.Text(
              'Showing first 100 of ${filteredTransactions.length} transactions.',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
            ),
          ),
      ],
    );
  }
}
